const fs=require('fs'),assert=require('assert/strict'),path=require('path');
const base=path.resolve(__dirname,'..'),src=fs.readFileSync(path.join(base,'htdocs/luci-static/resources/view/homevpn/overview.js'),'utf8');
const adapter=fs.readFileSync(path.join(__dirname,'acme-discovery-ui-test.cjs'),'utf8');
const {Node,E,all}=new Function(adapter.slice(adapter.indexOf('class Node'),adapter.indexOf('const tick'))+'; return {Node,E,all};')();
String.prototype.format=function(...a){let i=0;return this.replace(/%s/g,()=>a[i++]);};
async function main(){
 let pending, calls=[],state={enabled:true,running:true,conn_loaded:true,listening:true,pki_ready:true,san_ok:true,input_rules:true,mode:'selfsigned',remote:'old.example',clients:[{user:'active-user',vip:'10.0.0.2',remote_ip:'1.2.3.4'}]},answer={ok:true},reject=false,statusReject=false,deferRead=false,finishStatus;
 const rpc={declare:d=>(...a)=>{calls.push([d.method,...a]);if(d.method==='set_enabled')return new Promise((resolve,rejector)=>pending=()=>reject?rejector(new Error('network error')):resolve(answer));if(d.method==='status')return deferRead?new Promise(resolve=>finishStatus=()=>resolve(state)):statusReject?Promise.reject(new Error('status disconnected')):Promise.resolve(state);return Promise.resolve({});}};
 const ui={createHandlerFn:(_,f)=>f,addNotification(){},showModal(){},hideModal(){}};
 const v=new Function('view','rpc','ui','E','_','location','history','document',src)({extend:x=>x},rpc,ui,E,x=>x,{hash:'',reload(){throw Error('must preserve drafts');}},{},{createTextNode:x=>x});
 const root=v.render([state,{},{ip_mode:'subnet',pool_subnet:'invalid',cert_mode:'acme',acme_domain:''}]);
 const nodes=all(root),button=nodes.find(n=>n.attrs.id==='homevpn-toggle'),status=nodes.find(n=>n.attrs.id==='homevpn-toggle-status');
 assert(button,'independent master control exists');
 const text=n=>n==null?'':typeof n==='object'?n.textContent+n.children.map(text).join(''):String(n);
 const row=label=>all(root).find(n=>n.tag==='tr' && text(n.children[0])===label);
 const value=label=>text(row(label).children[1]);
 assert.equal(value('strongSwan (charon)'), '✓ running');
 const drafts=all(root).filter(n=>['input','textarea','select'].includes(n.tag));
 drafts.forEach((n,i)=>n.value='unsaved-'+i);
 let p=button.listeners.click();assert.equal(button.disabled,true);await button.listeners.click();assert.equal(calls.filter(c=>c[0]==='set_enabled').length,1);assert.deepEqual(calls[0],['set_enabled',false]);
 state={enabled:false,running:false,conn_loaded:false};pending();await p;assert.equal(button.disabled,false);assert.match(status.textContent,/Disabled/);assert.equal(calls.filter(c=>c[0]==='set_settings').length,0);
 assert.equal(value('strongSwan (charon)'), '✗ stopped', 'server details must follow successful off readback');
 assert.equal(value('Connection loaded in charon'), '✗ not loaded');
 assert.equal(value('Listening (500/4500)'), '✗ no');
 assert.equal(value('Connected clients'), '0');
 assert(!text(root).includes('active-user'),'old client details removed');
 assert.equal(value('Server certificate / CA'),'✗ missing');
 assert.equal(value('Firewall INPUT rules (500/4500/ESP)'),'✗ missing');
 state={enabled:true,running:true,conn_loaded:true,listening:true,clients:[{user:'new-user',vip:'10.0.0.3',remote_ip:'2.3.4.5'}],remote:'new.example',applied_mode:'subnet',applied_pool:'10.1.0.0/24',precheck:'refused',precheck_reason:'fixture reason',cert:{issuer:'fresh issuer',subject:'fresh subject'}};
 p=button.listeners.click();pending();await p;
 assert.deepEqual(calls.filter(c=>c[0]==='set_enabled').at(-1),['set_enabled',true]);
 assert.equal(value('strongSwan (charon)'), '✓ running');
 assert.equal(value('Connection loaded in charon'),'✓ loaded');
 assert.equal(value('Listening (500/4500)'),'✓ yes');
 assert.equal(value('Connected clients'),'1');
 assert.equal(value('Server address (clients dial)'),'new.example');
 assert.equal(value('Issuer'),'fresh issuer','certificate read-only details refreshed');
 assert(text(root).includes('new-user'));assert(text(root).includes('fixture reason'));
 assert(value('IP allocation mode (applied)').includes('10.1.0.0/24'));
 state={enabled:false,running:false,conn_loaded:false,clients:[]};
 drafts.forEach((n,i)=>{assert(all(root).includes(n),'draft node retained');assert.equal(n.value,'unsaved-'+i);});
 answer={ok:false,error:'conflict'};p=button.listeners.click();pending();await p;assert.match(status.textContent,/conflict/);assert.equal(button.disabled,false);
 reject=true;p=button.listeners.click();pending();await p;assert.match(status.textContent,/network error/);assert.equal(button.disabled,false);
 assert.equal(value('strongSwan (charon)'),'✗ stopped','failed action still paints actual readback');
 assert(!text(root).includes('fixture reason'),'stale precheck removed');
 deferRead=true;reject=false;answer={ok:true};p=button.listeners.click();pending();
 await new Promise(r=>setImmediate(r));assert.equal(button.disabled,true,'busy until readback completes');
 const n=calls.filter(c=>c[0]==='set_enabled').length;await button.listeners.click();assert.equal(calls.filter(c=>c[0]==='set_enabled').length,n,'no overlapping readbacks or stale response race');
 finishStatus();await p;deferRead=false;
 statusReject=true;reject=false;answer={ok:true};p=button.listeners.click();pending();await p;
 assert.match(status.textContent,/status disconnected/);
 assert(!row('strongSwan (charon)'),'unknown state must not leave stale running/stopped details');
 assert.equal(button.disabled,true,'unknown state blocks blind repeated toggles');
 drafts.forEach((n,i)=>{assert(all(root).includes(n));assert.equal(n.value,'unsaved-'+i);});
 console.log('PASS real view: independent boolean toggle, invalid drafts, busy/repeat, status readback, backend and transport errors, no reload');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
