#!/bin/sh
# Exercise the real ownership gate in target ash, with isolated disk fixtures.
set -eu
ROOT="$(cd "$1" && pwd)"
T="$(mktemp -d /tmp/hv-ownership.XXXXXX)"
trap 'rm -rf "$T"' EXIT
mkdir -p "$T/etc/swanctl/conf.d" "$T/var/swanctl" "$T/bin"
printf 'hv_with_lock() { "$@"; }\n' > "$T/lock.sh"
sed -e "s|/usr/share/homevpn/service-lock.sh|$T/lock.sh|g" \
    -e "s|/etc/swanctl|$T/etc/swanctl|g" \
    -e "s|/var/swanctl|$T/var/swanctl|g" \
    "$ROOT/usr/share/homevpn/service-control.sh" > "$T/control.sh"
printf '#!/bin/sh\nexit 1\n' > "$T/bin/pidof"
printf '#!/bin/sh\n[ ! -e "%s/remote" ] || echo "ipsec.other=remote"\n' "$T" > "$T/bin/uci"
chmod +x "$T/bin/"*
PATH="$T/bin:$PATH"
export PATH
extra_command() { :; }
. "$T/control.sh"
printf 'include conf.d/*.conf\ninclude %s/var/swanctl/swanctl.conf\n' "$T" > "$T/etc/swanctl/swanctl.conf"
N=0
check() {
    local expected="$1" label="$2" rc=0
    hv_exclusive > "$T/output" 2>&1 || rc=$?
    if [ "$expected" = pass ]; then
        [ "$rc" = 0 ] || { echo "FAIL $label: expected acceptance"; cat "$T/output"; exit 1; }
    else
        [ "$rc" != 0 ] || { echo "FAIL $label: expected refusal"; exit 1; }
    fi
    N=$((N + 1))
    echo "PASS $label"
}
printf '# generated by /etc/init.d/swanctl\n# Global config\n\npools {\n}\nsecrets {\n}\n' > "$T/var/swanctl/swanctl.conf"
check pass vendor-empty-skeleton
printf '# comment\n \t\r\n' > "$T/var/swanctl/swanctl.conf"
check pass comments-whitespace
printf ' pools {} secrets { } # comment\n' > "$T/var/swanctl/swanctl.conf"
check pass compact-empty-containers
printf 'pools\n{\n}\nsecrets\n{\n}\n' > "$T/var/swanctl/swanctl.conf"
check pass split-empty-containers
for content in \
    'pools { foreign { addrs = 192.0.2.0/24 } }' \
    'secrets { eap-foreign { secret = fixture } }' \
    'include /elsewhere/*.conf' \
    'pools { include /elsewhere/*.conf }' \
    'connections { foreign {} }' \
    'authorities {}' \
    'pools {' \
    'pools } {' \
    'pools {} trailing' \
    'pools { } secrets { } include /elsewhere/*.conf'; do
    printf '%s\n' "$content" > "$T/var/swanctl/swanctl.conf"
    check fail "foreign-or-malformed: $content"
done
printf 'pools {} secrets {}\n' > "$T/var/swanctl/swanctl.conf"
touch "$T/remote"
check fail uci-remote-even-with-empty-generated-file
rm "$T/remote"
touch "$T/etc/swanctl/conf.d/other.conf"
check fail foreign-conf-d-file
rm "$T/etc/swanctl/conf.d/other.conf"
check pass clean-after-refusals
echo "PASS ownership regression: $N cases"
