#!/bin/sh /etc/rc.common
#
# Copyright (C) 2020-2022, IrineSistiana
#
# Copyright (C) 2023, sbwml <admin@cooluc.com>
#
# This file is part of mosdns.
#
# mosdns is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# mosdns is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

START=51
USE_PROCD=1

PROG=/usr/bin/mosdns
DUMP_FILE=/etc/mosdns/cache.dump
DUMP_FILE_DEFAULT=/usr/share/mosdns/cache.dump
CONF_PATH=/var/mosdns
DEFAULT_CONF=${CONF_PATH}/config.yaml

service_triggers() {
    procd_add_reload_trigger "mosdns"
}

reload_service() {
    stop
    sleep 1
    start
}

start_service() {
	# 检查目录是否存在
	if [ ! -d "$CONF_PATH" ]; then
	  # 如果目录不存在，则创建目录
	  mkdir -p "$CONF_PATH"
	  echo "Directory created: $CONF_PATH"
	  cp /etc/mosdns/* ${CONF_PATH}/
	fi
	
    procd_open_instance mosdns
    procd_set_param env QUIC_GO_DISABLE_RECEIVE_BUFFER_WARNING=true
    procd_set_param command $PROG start
    procd_append_param command -c "$DEFAULT_CONF"
    procd_append_param command -d "/etc/mosdns"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance mosdns
    echo MOSDNS START
}

stop_service() {
    echo MOSDNS STOP
}
