#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.softethervpn
	set firewall.softethervpn=include
	set firewall.softethervpn.type=script
	set firewall.softethervpn.path=/var/etc/softethervpn.include
	set firewall.softethervpn.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@homeconnect[-1]
	add ucitrack homeconnect
	set ucitrack.@homeconnect[-1].init=homeconnect
	commit ucitrack
EOF

/etc/init.d/softethervpnbridge disable && /etc/init.d/softethervpnbridge stop
/etc/init.d/softethervpnclient disable && /etc/init.d/softethervpnclient stop
/etc/init.d/softethervpnserver disable && /etc/init.d/softethervpnserver stop
chmod +x /etc/init.d/homeconnect
rm -rf /tmp/luci-*cache
exit 0
