#!/bin/sh /etc/rc.common

START=95

. /etc/beamInDocker/dockerControl.sh

start() {
	local vt_enabled=$(uci -q get beamInDocker.beam.enabled)
	if [ "$vt_enabled" -eq "0" ]; then
		isContainerRunning
		[ "$?" -ne  "0" ] && stopContainer
		return 1
	fi
	
	startContainer
}

stop() {
	stopContainer
}