#!/bin/sh
# The master switch owns the whole strongSwan service, never just a connection.
. /usr/share/homevpn/service-lock.sh

hv_error() { echo "homevpn: $*" >&2; return 1; }

hv_exclusive() {
	local f conns
	# Fail closed on foreign disk configurations, including not-yet-loaded ones.
	for f in /etc/swanctl/conf.d/*; do
		[ -e "$f" ] || continue
		case "$f" in /etc/swanctl/conf.d/homevpn.conf|/etc/swanctl/conf.d/homevpn-eap.conf) ;;
		*) hv_error "strongSwan conflict: foreign configuration $f"; return 1;; esac
	done
	# The root config may only contain the standard includes; arbitrary includes
	# or inline configuration need a manual ownership review, not a guess.
	if [ -f /etc/swanctl/swanctl.conf ]; then
		awk ' { sub(/#.*/, ""); gsub(/^[ \t]+|[ \t]+$/, ""); }
			$0 != "" && $0 != "include conf.d/*.conf" && $0 != "include /var/swanctl/swanctl.conf" { bad=1 }
			END { exit bad }' /etc/swanctl/swanctl.conf || {
			hv_error 'strongSwan conflict: nonstandard swanctl.conf'; return 1;
		}
	fi
	# This include is generated by the independent ipsec UCI service. With no
	# remotes it must be empty; never infer ownership from an inactive daemon.
	if [ -e /var/swanctl/swanctl.conf ]; then
		[ -f /var/swanctl/swanctl.conf ] && [ -r /var/swanctl/swanctl.conf ] &&
			awk '{ sub(/#.*/, ""); if ($0 ~ /[^ 	\r]/) bad=1 } END { exit bad }' /var/swanctl/swanctl.conf || {
			hv_error 'strongSwan conflict: unowned /var/swanctl/swanctl.conf (including nested includes)'; return 1;
		}
	fi
	# UCI remotes are rendered into /var/swanctl, not conf.d. Even an inactive
	# remote is another owner's configuration and blocks exclusive takeover.
	if uci -q show ipsec | grep -q '=remote$'; then
		hv_error 'strongSwan conflict: ipsec UCI remote configuration'; return 1
	fi
	# Inspect connection headers in our generated file as well. This conservative
	# parser rejects extra connection names, including multiple names on a line.
	for f in /etc/swanctl/conf.d/homevpn.conf /etc/swanctl/conf.d/homevpn-eap.conf; do
		[ -s "$f" ] || continue
		awk '
		{ sub(/#.*/, ""); if ($0 ~ /(^|[{}; 	])include[ 	]/) bad=1;
		  gsub(/\{/, "\n{\n"); gsub(/\}/, "\n}\n"); n=split($0,a,"\n");
		  for(i=1;i<=n;i++){ s=a[i]; gsub(/^[ \t]+|[ \t]+$/, "",s); if(s=="")continue;
		    if(s=="{"){ if(depth==0) section=prev; if(section=="connections" && depth==1 && prev!="homevpn-eap")bad=1; depth++ }
		    else if(s=="}")depth--; else prev=s;
		  }
		} END { exit (bad || depth!=0) }' "$f" || {
			hv_error "strongSwan conflict: nonstandard configuration in $f"; return 1;
		}
	done
	if pidof charon >/dev/null; then
		conns="$(swanctl --list-conns 2>/dev/null)" || {
			hv_error 'Cannot verify strongSwan ownership: VICI unavailable.'; return 1;
		}
		if printf '%s\n' "$conns" | grep '^[^[:space:]].*:' | grep -qv '^homevpn-eap:'; then
			hv_error 'strongSwan conflict: another connection is loaded'; return 1
		fi
	fi
	return 0
}

hv_install_guard() {
	local target=/etc/init.d/swanctl tmp
	grep -q '^# homevpn-service-guard-v1$' "$target" && return 0
	# Adapt only known function declarations, never overwrite a vendor script
	# blindly. The original implementation remains in place for package upgrades.
	tmp="$(mktemp /etc/init.d/.homevpn-swanctl.XXXXXX)" || return 1
	if ! awk '
	/^start_service\(\) \{$/ { sub(/start_service/, "hv_original_start_service"); a++ }
	/^reload_service\(\) \{$/ { sub(/reload_service/, "hv_original_reload_service"); b++ }
	/^service_triggers\(\) \{$/ { sub(/service_triggers/, "hv_original_service_triggers"); c++ }
	{print} END { if(a!=1 || b!=1 || c!=1)exit 1 }' "$target" > "$tmp"; then
		rm -f "$tmp"; hv_error 'Unsupported swanctl init script; no service state changed.'; return 1
	fi
	cat >> "$tmp" <<'GUARD'

# homevpn-service-guard-v1
# Added by HomeVPN on exclusive takeover. No daemon is restarted to install it.
# Package upgrades replacing swanctl must re-install the guard before enabling.
hv_swanctl_dispatch() {
	[ "$(uci -q get homevpn.config.enabled)" != 0 ] || return 0
	"$@"
}
hv_swanctl_guard() {
	if [ -r /usr/share/homevpn/service-lock.sh ]; then
		. /usr/share/homevpn/service-lock.sh
		hv_with_lock hv_swanctl_dispatch "$@"
	else
		hv_swanctl_dispatch "$@"
	fi
}
start_service() { hv_swanctl_guard hv_original_start_service "$@"; }
reload_service() { hv_swanctl_guard hv_original_reload_service "$@"; }
service_triggers() { hv_swanctl_dispatch hv_original_service_triggers "$@"; }
GUARD
	sh -n "$tmp" && chmod 755 "$tmp" && mv "$tmp" "$target" || {
		rm -f "$tmp"; hv_error 'Failed to install swanctl service guard'; return 1;
	}
}

hv_ready() {
	pidof charon >/dev/null && swanctl --list-conns 2>/dev/null | grep -q '^homevpn-eap:'
}

hv_stop_engine() {
	local i=0
	# rc.common stop removes the procd instance/respawn and its triggers, then
	# SIGTERM lets charon remove its SAs/XFRM policies. Never kill a respawn PID.
	/etc/init.d/swanctl stop || { hv_error 'strongSwan stop failed'; return 1; }
	while pidof charon >/dev/null; do
		i=$((i + 1)); [ "$i" -lt 15 ] || { hv_error 'strongSwan is still running after stop'; return 1; }
		sleep 1
	done
	return 0
}

hv_cleanup_network() {
	local name old_mode old_pool pool routes failed=0
	old_mode="$(state_get mode)"; old_pool="$(state_get pool)"
	drop_client_include || failed=1
	for name in homevpn_isakmp homevpn_nat_t homevpn_esp homevpn_client_input homevpn_client_fwd; do
		if uci -q get "firewall.$name" >/dev/null; then
			uci -q delete "firewall.$name" || failed=1
		fi
	done
	uci -q commit firewall || failed=1
	/etc/init.d/firewall reload || failed=1
	[ "$old_mode" = subnet ] || old_pool=
	# The attempted pool is journaled before apply_config: it may have installed
	# the route and then failed before writing STATE_FILE.
	for pool in $old_pool ${hv_pending_pool:-}; do
		routes="$(ip route show dev lo 2>/dev/null)" || { failed=1; continue; }
		if printf '%s\n' "$routes" | awk -v p="$pool" '$1==p { found=1 } END { exit !found }'; then
			ip route del "$pool" dev lo 2>/dev/null || failed=1
		fi
	done
	# Keep static DHCP reservations until next enable: removing them requires a
	# dnsmasq restart, which needlessly interrupts non-VPN LAN users on disable.
	return "$failed"
}

hv_set_enabled() {
	local wanted="$1" i hv_pending_pool=
	case "$wanted" in 0|1) ;; *) hv_error 'enabled must be 0 or 1'; return 1;; esac
	hv_exclusive || return 1
	hv_install_guard || return 1
	if [ "$wanted" = 0 ]; then
		# Persist first: every start/reload path observes off before stopping.
		local failed=0
		uci -q set homevpn.config.enabled=0 && uci -q commit homevpn || { hv_error 'Failed to persist disabled state'; failed=1; }
		/etc/init.d/swanctl disable || { hv_error 'strongSwan boot disable failed'; failed=1; }
		hv_stop_engine || failed=1
		hv_cleanup_network || { hv_error 'Network cleanup failed; residual rules or routes may remain'; failed=1; }
		return "$failed"
	fi
	if [ "$(hv_get enabled)" != 0 ] && hv_ready; then return 0; fi
	# Precheck before changing desired state or starting anything. In particular,
	# do not use the historical start failure path that restarted stale configs.
	load_env
	[ -n "$LAN_ADDR" ] || { refuse_no_lan; return 1; }
	precheck || return 1
	provision_certs || { hv_error 'Certificate provisioning failed'; return 1; }
	[ "${MODE:-}" != subnet ] || hv_pending_pool="$POOL_SUBNET"
	if uci -q set homevpn.config.enabled=1 && uci -q commit homevpn &&
		/etc/init.d/homevpn enable && /etc/init.d/swanctl enable && ensure_firewall && apply_config start; then
		i=0
		while [ "$i" -lt 10 ]; do
			hv_ready && return 0
			i=$((i + 1)); sleep 1
		done
	fi
	# Do not claim success just because procd accepted a start request.
	uci -q set homevpn.config.enabled=0 && uci -q commit homevpn || hv_error 'Rollback: failed to persist disabled state'
	/etc/init.d/swanctl disable || hv_error 'Rollback: boot disable failed'
	hv_stop_engine || hv_error 'Rollback: strongSwan may still be running'
	hv_cleanup_network || hv_error 'Rollback: residual network rules or routes may remain'
	hv_error 'HomeVPN enable failed; rollback attempted (see errors above).'
	return 1
}

extra_command "set-enabled" "Set the persistent master switch (0 or 1)"
set-enabled() { hv_with_lock hv_set_enabled "$@"; }
start_service() { hv_with_lock hv_start "$@"; }
regen() { hv_with_lock hv_regen "$@"; }
sync-acme() { hv_with_lock hv_sync_acme "$@"; }
stop_service() { hv_with_lock hv_stop; }
hv_stop() { hv_exclusive && hv_stop_engine; }
