#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@AdGuardHome[-1]
	add ucitrack AdGuardHome
	set ucitrack.@AdGuardHome[-1].init=AdGuardHome
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
