#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@homeledeDnsBundle[-1]
	add ucitrack homeledeDnsBundle
	set ucitrack.@homeledeDnsBundle[-1].init=homeledeDnsBundle
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
