#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@chinadns-ng[-1]
	add ucitrack chinadns-ng
	set ucitrack.@chinadns-ng[-1].init=chinadns-ng
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
chmod +x /usr/share/chinadns-ng/chinadns-ng_update.sh
exit 0
