#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@beamInDocker[-1]
	add ucitrack beamInDocker
	set ucitrack.@beamInDocker[-1].init=beamInDocker
	commit ucitrack
EOF

/etc/init.d/beamInDocker disable && /etc/init.d/beamInDocker stop
chmod +x /etc/beamInDocker/*.sh
chmod +x /etc/init.d/beamInDocker
rm -rf /tmp/luci-*cache
exit 0
