#!/bin/sh /etc/rc.common
#
# Copyright (C) 2018-2020 xiaoqingfeng(Richard) <xiaoqingfengatgm@gmail.com>.
#

START=18
NAME=dnsmasq-china-list

start()
{
	/etc/dnsmasq-china-list/refreshConf.sh
	echo "[Service]dnsmasq-china-list started."
}

stop()
{
	/etc/dnsmasq-china-list/clearConf.sh
	echo "[Service]dnsmasq-china-list stoped."
}

reload()
{
	stop
	start
}
